// import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/carousel/styles.css";
import { ColorSchemeScript, MantineProvider, createTheme } from "@mantine/core";
import Header from "@/components/layout/header.tsx/header";
import { Footer } from "@/components/layout/footer/footer";

const roboto = Roboto({ subsets: ["latin", "cyrillic"], weight: "400" });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

const theme = createTheme({
	colors: {
		dark: [
			"#C8D7DF",
			"#3A5664",
			"#334B57",
			"#2B404A",
			"#24353D",
			"#1C2A30",
			"#151E23",
			"#0D1316",
			"#080B0D",
			"#020303",
		],
	},
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
				<link rel="icon" href="./logoDarkFooter.png" sizes="any" />
			</head>
			<body className={roboto.className}>
				<MantineProvider theme={theme} defaultColorScheme="auto">
					<Header />
					<main>{children}</main>
					<Footer />
				</MantineProvider>
			</body>
		</html>
	);
}
